# Change these first
owner: pixiumdigital # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Boldly
    url: https://live.boldly.app/ping.html
  - name: Kaminoo
    url: https://app.kaminoo.com/ping.html
  - name: GMC
    url: https://gomastercoach-app.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # baseUrl: /uptime
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://avatars2.githubusercontent.com/u/32156123?s=400&u=724718b5e3546c70b79e0bebe407a9f6873c8b6d&v=4
  name: Pixium Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: https://pixiumdigital.github.io/uptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
