# Change these first
owner: pixiumdigital # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Aeqlia Platform
    url: https://app.aeqlia.com/ping.html
  - name: Boldly
    url: https://live.boldly.app/ping.html
  - name: Kaminoo
    url: https://app.kaminoo.com/ping.html
  - name: GMC
    url: https://gomastercoach-app.com
  - name: Pixium Digital
    url: https://pixiumdigital.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # baseUrl: /uptime
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://avatars2.githubusercontent.com/u/32156123?s=400&u=724718b5e3546c70b79e0bebe407a9f6873c8b6d&v=4
  name: Pixium Uptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: https://pixiumdigital.github.io/uptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
